### ISSUE TITLE
Bug Local Variable 'div_idx' 

### ISSUE THREAD

**Issue by louis78100** [hcederna/notes-email#1]
There is a bug when I tried to run the notes_email.py file.
In line 38 in format_learning_notes.py in the the function format_learning_notes.
You are using a unassigned variable 'div_idx'
I tried to look in other files where this variable were use, but I didn't find it

**Comment by hcederna** [comment]
All fixed - should be good to go!

**Comment by hcederna** [comment]
All fixed - should be good to go!
